---
- name: Install AD from an MSI 
  hosts: all 
 
  tasks:
    - name: Remove EC3 computer from Active Directory using a windows machine
      win_domain_computer:
         name: EC3
         state: absent
      delegate_to: WIN-SKS85NBQU1H.mylab.com