---
- name: Hello World Sample
  hosts: 10.100.152.118
  tasks:
    - name: Ansible logs
      uri:
        url: -k -L https://10.100.152.118:/api/v2/jobs/26
        user: "admin"
        password: "Bharath_009"
        method: GET
        force_basic_auth: yes
        status_code: 201