---
- name: Hello World Sample
  hosts: all
  tasks:
    - name: Ansible logs
      uri:
        url: -k -L https://192.168.162.136:/api/v2/jobs/34
        user: "admin"
        password: "Bharath_009"
        method: GET
        force_basic_auth: yes
        status_code: 201
