---
- name: get Logs Ansible automation Job templet 
  hosts: all
  tasks:
    - name: Ansible logs
      uri:
        url: -k -L https://192.168.162.136:/api/v2/jobs/34
        user: "admin"
        password: "8612"
        method: GET
        force_basic_auth: yes
        status_code: 201
