---
# This playbook tests the script module on Windows hosts
- name: remove ad objects 
  hosts: all 
  vars:
    Instance_name: testcmp
  gather_facts: false

  tasks: 
    - name: Ensure user bob is absent
      win_domain_computer:
        name: bob
        state: present
        dns_hostname: newhost.ansible.local
        ou: 'OU=myOU,DC=mylab,DC=com'
      register: computer_status

    - name: remove Ad computer usng powershell script
      script: files/Remove-Ad.ps1 bob
      when: computer_status.exists == false

    # - name: Remove linux computer from Active Directory using a windows machine
    #   win_domain_computer:
    #     name: one_linux_server
    #     state: absent
    #   delegate_to: my_windows_bridge.my_org.local

      #args: "{{Instance_name}}"
      #vars:
        #name_tag: "instances[*].tags.name"
