---
# This playbook tests the script module on Windows hosts
- name: remove ad objects 
  hosts: all 
  vars:
    Instance_name: testcmp
  gather_facts: false

  tasks:
    - name: remove Ad computer usng powershell script
      script: files/Remove-Ad.ps1 testcmp
      #args: "{{Instance_name}}"
      #register: _out


       #vars:
        #name_tag: "instances[*].tags.name"
