---
# This playbook tests the script module on Windows hosts
- name: remove ad objects 
  hosts: all 
  vars:
    Instance_name: testcmp
  gather_facts: false

  tasks: 
    - name: Ensure user ec3 is absent
      win_domain_computer:
        name: testcp
        state: present
        dns_hostname: newhost.ansible.local
        ou: 'OU=myOU,DC=mylab,DC=com'
      register: computer_status

    # - name: Remove linux computer from Active Directory using a windows machine
    #   community.windows.win_domain_computer:
    #     name: ec3
    #     state: absent
    #   delegate_to: mylab.com

    # - name: remove Ad computer usng powershell script
    #   script: files/Remove-Ad.ps1 testcmp
      #args: "{{Instance_name}}"
      #vars:
        #name_tag: "instances[*].tags.name"
